# See https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/scanners/sonarscanner/
# Scan all relevant files.
sonar.sources=./images/gra-wren-state-api/src/main/java

# Exclude test and config files
sonar.coverage.exclusions=images/gra-wren-state-api/src/test/**,images/gra-wren-state-api/src/main/resources/**

# Ignore specific rules for config and test files
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=images/gra-wren-state-api/src/main/resources/application.properties
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S1192
sonar.issue.ignore.multicriteria.e2.resourceKey=images/gra-wren-state-api/src/main/resources/log4j2.xml

# Exclude specific files and directories from code duplication analysis
sonar.cpd.exclusions=images/gra-wren-state-api/src/test/**,images/gra-wren-state-api/src/main/resources/**

# Declare the tests folder
sonar.tests=./images/gra-wren-state-api/src/test/java

# Java binaries (for coverage)
sonar.java.binaries=./images/gra-wren-state-api/target

# Coverage report paths
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=./images/gra-wren-state-api/target/site/jacoco/jacoco.xml

# Enable duplication detection
sonar.cpd.enabled=true
